// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webionic.BloodPressure.Data;

#nullable disable

namespace Webionic.BloodPressure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Webionic.BloodPressure.Models.BloodPressureEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diastole")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pulse")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Systole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredAt");

                    b.ToTable("BloodPressureEntries");
                });

            modelBuilder.Entity("Webionic.BloodPressure.Models.ReminderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FridayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MondayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SaturdayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SundayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ThursdayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TuesdayEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WednesdayEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReminderSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FridayEnabled = true,
                            IsEnabled = false,
                            MondayEnabled = true,
                            ReminderTime = new TimeOnly(8, 0, 0),
                            SaturdayEnabled = true,
                            SundayEnabled = true,
                            ThursdayEnabled = true,
                            TuesdayEnabled = true,
                            WednesdayEnabled = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
